name: Production Edubot

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: GIT pulling from github repository
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        PORT: ${{ secrets.SSH_PORT }}
        KEY: ${{ secrets.SSH_KEY }}
        source: "."
        target: "/root/bot/edu-list"

    - name: Command using from script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        PORT: ${{ secrets.SSH_PORT }}
        KEY: ${{ secrets.SSH_KEY }}
        script_stop: true
        script: |
          /root/bot/edu-list/venv/bin/pip install -r /root/bot/edu-list/requirements.txt
          pm2 restart edubot
          systemctl restart edubot.service
          sh /root/devops/deploy.sh "${{ github.event.head_commit.message }}" "Edu bot updates"
